/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 11 19:09:23 GMT 2019
 */

package simpleproject;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import simpleproject.SumOperator;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SumOperator_ESTest extends SumOperator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SumOperator sumOperator0 = new SumOperator();
      int int0 = sumOperator0.sum(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SumOperator sumOperator0 = new SumOperator();
      int int0 = sumOperator0.sum(2801, 169);
      assertEquals(2970, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SumOperator sumOperator0 = new SumOperator();
      int int0 = sumOperator0.sum((-1), 0);
      assertEquals((-1), int0);
  }
}
