///*
// * This file was automatically generated by EvoSuite
// * Thu May 02 12:13:13 GMT 2019
// */
//
//package com.pa;
//
//import static org.evosuite.runtime.EvoAssertions.*;
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.assertNull;
//import static org.junit.Assert.assertSame;
//import static org.junit.Assert.fail;
//
//import java.util.HashMap;
//import java.util.LinkedList;
//import java.util.Map;
//
//import org.evosuite.runtime.mock.java.util.MockDate;
//import org.junit.Test;
//
//import com.pa.analyzer.GroupAnalyzer;
//import com.pa.analyzer.GroupResult;
//import com.pa.comparator.SetResearcherResult;
//import com.pa.entity.Group;
//import com.pa.entity.QualisData;
//import com.pa.entity.Researcher;
//import com.pa.util.EnumPublicationLocalType;
//
////@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
//public class _GroupAnalyzer_ESTest {
//
//  @Test(timeout = 4000)
//  public void test0()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      Group group0 = new Group();
//      // Undeclared exception!
//      try { 
//        groupAnalyzer0.analyzerGroup(group0, (Map<EnumPublicationLocalType, QualisData>) null);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("com.pa.comparator.SetResearcherMetrics", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      Group group0 = new Group("");
//      HashMap<EnumPublicationLocalType, QualisData> hashMap0 = new HashMap<EnumPublicationLocalType, QualisData>();
//      SetResearcherResult setResearcherResult0 = groupAnalyzer0.analyzerGroup(group0, hashMap0);
//      assertEquals(Double.NaN, setResearcherResult0.getConcludedOrientations(), 0.01);
//  }
//
//  @Test(timeout = 4000)
//  public void test2()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      HashMap<EnumPublicationLocalType, QualisData> hashMap0 = new HashMap<EnumPublicationLocalType, QualisData>();
//      SetResearcherResult setResearcherResult0 = groupAnalyzer0.analyzerGroup((Group) null, hashMap0);
//      assertNull(setResearcherResult0);
//  }
//
//  @Test(timeout = 4000)
//  public void test3()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      Group group0 = new Group();
//      LinkedList<Researcher> linkedList0 = new LinkedList<Researcher>();
//      group0.setCurriculos(linkedList0);
//      MockDate mockDate0 = new MockDate((-1), (-1), (-2656), (-1), 2693, 2693);
//      Researcher researcher0 = new Researcher("G$~]h.p=osE=", mockDate0);
//      linkedList0.add(researcher0);
//      GroupResult groupResult0 = groupAnalyzer0.groupResult(group0, (Map<EnumPublicationLocalType, QualisData>) null);
//      assertEquals(0, groupResult0.getConcludedOrientations());
//  }
//
//  @Test(timeout = 4000)
//  public void test4()  throws Throwable  {
//      Group group0 = new Group();
//      HashMap<EnumPublicationLocalType, QualisData> hashMap0 = new HashMap<EnumPublicationLocalType, QualisData>();
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      // Undeclared exception!
//      try { 
//        groupAnalyzer0.groupResult(group0, hashMap0);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("com.pa.analyzer.GroupAnalyzer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test5()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      HashMap<EnumPublicationLocalType, QualisData> hashMap0 = new HashMap<EnumPublicationLocalType, QualisData>();
//      GroupResult groupResult0 = groupAnalyzer0.groupResult((Group) null, hashMap0);
//      assertNull(groupResult0);
//  }
//
//  @Test(timeout = 4000)
//  public void test6()  throws Throwable  {
//      GroupAnalyzer groupAnalyzer0 = GroupAnalyzer.getInstance();
//      GroupAnalyzer groupAnalyzer1 = GroupAnalyzer.getInstance();
//      assertSame(groupAnalyzer1, groupAnalyzer0);
//  }
//}
