/*
 * This file was automatically generated by EvoSuite
 * Mon May 20 21:34:50 GMT 2019
 */
package net.kencochrane.a4j.DAO;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.DAO.Product;
import net.kencochrane.a4j.beans.FullProduct;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;

public class Product_ESTest {

    public static Product test0_0() throws Throwable {
        return new Product();
    }

    public static FullProduct test0_1() throws Throwable {
        Product product0 = new Product();
        return product0.getProduct("", "", "");
    }

    public static Product test1_0() throws Throwable {
        return new Product();
    }

    public static EvoSuiteFile test1_1() throws Throwable {
        Product product0 = new Product();
        return new EvoSuiteFile("/S20 RB@[1CWC1K_NET.KENCOCHRANE.A4J.BEANS.TRACKS_HEAVY_OO>(6 U7AUR<-MV [G.XML");
    }

    public static void test1_2() throws Throwable {
        Product product0 = new Product();
        EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/S20 RB@[1CWC1K_NET.KENCOCHRANE.A4J.BEANS.TRACKS_HEAVY_OO>(6 U7AUR<-MV [G.XML");
        FileSystemHandling.appendLineToFile(evoSuiteFile0, "*}Px{");
        return FileSystemHandling;
    }

    public static FullProduct test1_3() throws Throwable {
        Product product0 = new Product();
        EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/S20 RB@[1CWC1K_NET.KENCOCHRANE.A4J.BEANS.TRACKS_HEAVY_OO>(6 U7AUR<-MV [G.XML");
        FileSystemHandling.appendLineToFile(evoSuiteFile0, "*}Px{");
        return product0.getProduct("s20 rb@[1cWC1K", "net.kencochrane.a4j.beans.Tracks", "oO>(6 u7aUR<-mv [g");
    }
}
