/*
 * This file was automatically generated by EvoSuite
 * Mon May 20 21:45:37 GMT 2019
 */
package net.kencochrane.a4j.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import net.kencochrane.a4j.data.Query;

public class Query_ESTest {

    public static Query test00_0() throws Throwable {
        return new Query();
    }

    public static String test00_1() throws Throwable {
        Query query0 = new Query();
        return query0.BlendedSearchGenerator("**Be]nk7t7Os^$v8", "]IFk,g{FBf>636A}6R");
    }

    public static Query test01_0() throws Throwable {
        return new Query();
    }

    public static String test01_1() throws Throwable {
        Query query0 = new Query();
        return query0.SearchQueryGenerator((String) null, "", "", (String) null, (String) null, "");
    }

    public static Query test02_0() throws Throwable {
        return new Query();
    }

    public static String test02_1() throws Throwable {
        Query query0 = new Query();
        return query0.AddtoCart("~{imtM5!@H.", "~{imtM5!@H.");
    }

    public static Query test03_0() throws Throwable {
        return new Query();
    }

    public static ArrayList<String> test03_1() throws Throwable {
        Query query0 = new Query();
        return new ArrayList<String>();
    }

    public static Query test04_0() throws Throwable {
        return new Query();
    }

    public static String test04_1() throws Throwable {
        Query query0 = new Query();
        return query0.KeywordSearchGenerator("ShoppingCart=modify&f=xml&dev-t=", "3I|Llhj0b*R[h'", "3I|Llhj0b*R[h'", "mCaPQeGFGj]|n");
    }

    public static Query test05_0() throws Throwable {
        return new Query();
    }

    public static String test05_1() throws Throwable {
        Query query0 = new Query();
        return query0.browseNodeQueryGenerator("", "dev-t=", "", "dev-t=", "");
    }

    public static Query test06_0() throws Throwable {
        return new Query();
    }

    public static String test06_1() throws Throwable {
        Query query0 = new Query();
        return query0.SearchThirdPartyGenerator(":do[Z", "6?e=T|$l", "<VeQjhd", "<VeQjhd");
    }

    public static Query test07_0() throws Throwable {
        return new Query();
    }

    public static Query test08_0() throws Throwable {
        return new Query();
    }

    public static String test08_1() throws Throwable {
        Query query0 = new Query();
        return query0.ModifyCart("2>23FIq[>)uC]f)`ooi", "2>23FIq[>)uC]f)`ooi", "f?{'8xdo=HE", "2>23FIq[>)uC]f)`ooi");
    }

    public static Query test09_0() throws Throwable {
        return new Query();
    }

    public static String test09_1() throws Throwable {
        Query query0 = new Query();
        return query0.AddToExistingCart("Xd$}TG27W", "Xd$}TG27W", "!1N?x1!%Ubq?xF", "`W9&Vo:cv!TURCFL");
    }

    public static Query test10_0() throws Throwable {
        return new Query();
    }

    public static String test10_1() throws Throwable {
        Query query0 = new Query();
        return query0.GetItemsFromCart("'%qh2R", "'%qh2R");
    }

    public static Query test11_0() throws Throwable {
        return new Query();
    }

    public static String test11_1() throws Throwable {
        Query query0 = new Query();
        return query0.RemoveFromCart("ShoppingCart=clear&f=xml&dev-t=", "ShoppingCart=clear&f=xml&dev-t=", "ShoppingCart=clear&f=xml&dev-t=");
    }

    public static Query test12_0() throws Throwable {
        return new Query();
    }

    public static ArrayList<Object> test12_1() throws Throwable {
        Query query0 = new Query();
        return new ArrayList<Object>();
    }

    public static Query test13_0() throws Throwable {
        return new Query();
    }

    public static Query test14_0() throws Throwable {
        return new Query();
    }

    public static ArrayList<Object> test14_1() throws Throwable {
        Query query0 = new Query();
        return new ArrayList<Object>();
    }

    public static ArrayList<Object> test14_2() throws Throwable {
        Query query0 = new Query();
        ArrayList<Object> arrayList0 = new ArrayList<Object>();
        arrayList0.add((Object) "AsinSearch");
        return arrayList0;
    }

    public static ArrayList<Object> test14_3() throws Throwable {
        Query query0 = new Query();
        ArrayList<Object> arrayList0 = new ArrayList<Object>();
        arrayList0.add((Object) "AsinSearch");
        arrayList0.add((Object) "r<xoav0[.(lV");
        return arrayList0;
    }

    public static String test14_4() throws Throwable {
        Query query0 = new Query();
        ArrayList<Object> arrayList0 = new ArrayList<Object>();
        arrayList0.add((Object) "AsinSearch");
        arrayList0.add((Object) "r<xoav0[.(lV");
        return query0.generateMultipleSearchString("AsinSearch", arrayList0);
    }
}
