/*
 * This file was automatically generated by EvoSuite
 * Mon May 20 21:34:50 GMT 2019
 */

package net.kencochrane.a4j.DAO;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.DAO.Product;
import net.kencochrane.a4j.beans.FullProduct;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;

public class Product_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Product product0 = new Product();
      FullProduct fullProduct0 = product0.getProduct("", "", "");
      assertNull(fullProduct0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Product product0 = new Product();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/S20 RB@[1CWC1K_NET.KENCOCHRANE.A4J.BEANS.TRACKS_HEAVY_OO>(6 U7AUR<-MV [G.XML");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "*}Px{");
      FullProduct fullProduct0 = product0.getProduct("s20 rb@[1cWC1K", "net.kencochrane.a4j.beans.Tracks", "oO>(6 u7aUR<-mv [g");
      assertNotNull(fullProduct0);
  }
}
